/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Usuario;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Pestaña_Aulas extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Pestaña_Aulas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreAula = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxAula = new javax.swing.JComboBox<>();
        jComboBoxBloque = new javax.swing.JComboBox<>();
        Btn_Agregar_Aula = new javax.swing.JButton();
        Btn_Modificar_Aula = new javax.swing.JButton();
        Btn_Eliminar_Aula = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAulas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNmbreAula = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(700, 450));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreAula.setText("Aulas del bloque: ");
        add(jLabelNombreAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 30));

        jLabel3.setText("Aula");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 110, 30));

        jComboBoxAula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula" }));
        jComboBoxAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAulaActionPerformed(evt);
            }
        });
        add(jComboBoxAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 110, -1));

        jComboBoxBloque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bloque" }));
        jComboBoxBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBloqueActionPerformed(evt);
            }
        });
        add(jComboBoxBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, -1));

        Btn_Agregar_Aula.setBackground(new java.awt.Color(153, 255, 153));
        Btn_Agregar_Aula.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Agregar_Aula.setText("Agregar");
        Btn_Agregar_Aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_AulaActionPerformed(evt);
            }
        });
        add(Btn_Agregar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 110, 30));

        Btn_Modificar_Aula.setText("Modificar");
        add(Btn_Modificar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 110, 30));

        Btn_Eliminar_Aula.setBackground(new java.awt.Color(204, 0, 0));
        Btn_Eliminar_Aula.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Eliminar_Aula.setText("Eliminar");
        add(Btn_Eliminar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 110, 30));

        jLabel4.setText("Bloque");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        jTableAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Capacidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAulas);

        jScrollPane2.setViewportView(jScrollPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 470, 220));

        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel2.setText("Tipo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel5.setText("Capacidad:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));
        add(txtNmbreAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 190, -1));
        add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 190, -1));
        add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jComboBoxAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAulaActionPerformed

    private void jComboBoxBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBloqueActionPerformed

    private void Btn_Agregar_AulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_AulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Agregar_AulaActionPerformed

    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Agregar_Aula;
    public javax.swing.JButton Btn_Eliminar_Aula;
    public javax.swing.JButton Btn_Modificar_Aula;
    public javax.swing.JComboBox<String> jComboBoxAula;
    public javax.swing.JComboBox<String> jComboBoxBloque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelNombreAula;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableAulas;
    public javax.swing.JTextField txtCapacidad;
    public javax.swing.JTextField txtNmbreAula;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

}
