/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Usuario;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Pestaña_Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Pestaña_Usuarios() {
        initComponents();
        String columnas[] = {"Usuario","Tipo"};
        this.tabla.setColumnIdentifiers(columnas);
        this.Tabla_Usuarios.setModel(tabla);
        this.Tabla_Usuarios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (Tabla_Usuarios.getSelectedRow() != -1) {
                    actualizarCampos();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Agregar_U = new javax.swing.JButton();
        Btn_Modificar_U = new javax.swing.JButton();
        Btn_Eliminar_U = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Usuarios = new javax.swing.JTable();
        Txt_Clave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 250));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Agregar_U.setText("Agregar");
        Btn_Agregar_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_UActionPerformed(evt);
            }
        });
        add(Btn_Agregar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 130, 40));

        Btn_Modificar_U.setText("Modificar");
        add(Btn_Modificar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 130, 40));

        Btn_Eliminar_U.setText("Eliminar");
        add(Btn_Eliminar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 130, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_Usuarios.setGridColor(new java.awt.Color(102, 102, 102));
        Tabla_Usuarios.setRowHeight(30);
        Tabla_Usuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Tabla_Usuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 370, 350));
        add(Txt_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 210, 40));

        jLabel2.setText("Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 110, 30));

        jLabel3.setText("Contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 110, 30));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 150, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 130, 35));

        jLabel4.setText("Contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    public void ActualizarTablaUsuarios() {
        this.tabla.setRowCount(0);
        for (Usuario u : this.Usuarios) {
            this.tabla.addRow(new Object[]{u.getUsuario(),u.getTipo()});
        }
    }
    
    public void limpiarCampos() {
        this.jTextField1.setText("");
        this.Txt_Clave.setText("");
        this.jComboBox1.setSelectedIndex(0);
    }

    private void actualizarCampos() {
        for(Usuario u : this.Usuarios){
            if(u.getUsuario().matches(this.Tabla_Usuarios.getValueAt(this.Tabla_Usuarios.getSelectedRow(), 0).toString())){
                this.jTextField1.setText(u.getUsuario());
                this.Txt_Clave.setText(u.getClave());
                if(u.getTipo().matches("Admin")){
                    this.jComboBox1.setSelectedIndex(0);
                }else{
                    this.jComboBox1.setSelectedIndex(1);
                }
                return;
            }
        }
    }
    private void Btn_Agregar_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_UActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Btn_Agregar_UActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
    private ArrayList<Usuario> Usuarios = new ArrayList<>();

    public ArrayList<Usuario> getUsuarios() {
        return this.Usuarios;
    }

    public void setUsuarios(ArrayList<Usuario> Usuarios) {
        this.Usuarios = Usuarios;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Agregar_U;
    public javax.swing.JButton Btn_Eliminar_U;
    public javax.swing.JButton Btn_Modificar_U;
    public javax.swing.JTable Tabla_Usuarios;
    public javax.swing.JPasswordField Txt_Clave;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
