/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Docente;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class Pestaña_Docentes extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Pestaña_Docentes() {
        initComponents();
        String columnas[] = {"Docentes"};
        this.tabla.setColumnIdentifiers(columnas);
        this.jtblTabla_Docentes.setModel(tabla);
        this.jtblTabla_Docentes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jtblTabla_Docentes.getSelectedRow() != -1) {
                    actualizarCampos();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbtnAgregar = new javax.swing.JButton();
        jtbtnModificar = new javax.swing.JButton();
        jtbtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTabla_Docentes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNombreDocente = new javax.swing.JTextField();
        jtxtIdDocente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtCorreoDocente = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 250));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbtnAgregar.setText("Agregar");
        jtbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAgregarActionPerformed(evt);
            }
        });
        add(jtbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 130, 40));

        jtbtnModificar.setText("Modificar");
        add(jtbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 130, 40));

        jtbtnEliminar.setText("Eliminar");
        add(jtbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 130, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jtblTabla_Docentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblTabla_Docentes.setGridColor(new java.awt.Color(102, 102, 102));
        jtblTabla_Docentes.setRowHeight(30);
        jtblTabla_Docentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtblTabla_Docentes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, 350));

        jLabel2.setText("ID Docente");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 110, 30));

        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 110, 30));
        add(jtxtNombreDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, 40));
        add(jtxtIdDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 150, 40));

        jLabel4.setText("Correo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 110, 30));
        add(jtxtCorreoDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    
    public void actualizarTablaDocentes() {
    this.tabla.setRowCount(0);
    
    for (Docente d : this.docentes) {
        this.tabla.addRow(new Object[]{d.getNombre(), d.getEmail()});
    }
}


    private void actualizarCampos() {
    int filaSeleccionada = this.jtblTabla_Docentes.getSelectedRow();

    if (filaSeleccionada != -1) {
        String nombreDocenteSeleccionado = this.jtblTabla_Docentes.getValueAt(filaSeleccionada, 0).toString();

        for (Docente d : this.docentes) {
            if (d.getNombre().equals(nombreDocenteSeleccionado)) {
                this.jtxtIdDocente.setText(String.valueOf(d.getId()));
                this.jtxtNombreDocente.setText(d.getNombre());
                this.jtxtCorreoDocente.setText(d.getEmail());

                return;
            }
        }

        // Ejemplo:
        // this.jtxtNombreDocente.setText("");
        // this.Txt_Email.setText("");
    }
}

    private void jtbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAgregarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtbtnAgregarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
    private ArrayList<Docente> docentes = new ArrayList<>();

    public ArrayList<Docente> getDocentes() {
        return this.docentes;
    }

    public void setDocentes(ArrayList<Docente> docentes) {
        this.docentes = docentes;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtblTabla_Docentes;
    public javax.swing.JButton jtbtnAgregar;
    public javax.swing.JButton jtbtnEliminar;
    public javax.swing.JButton jtbtnModificar;
    public javax.swing.JTextField jtxtCorreoDocente;
    public javax.swing.JTextField jtxtIdDocente;
    public javax.swing.JTextField jtxtNombreDocente;
    // End of variables declaration//GEN-END:variables
    
}
