/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Materia;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class Pestaña_Materias extends javax.swing.JPanel {

    public Pestaña_Materias() {
        initComponents();
        String columnas[] = {"Materias", "Código"};
        this.tabla.setColumnIdentifiers(columnas);
        this.jtblTabla_Materias.setModel(tabla);
        this.jtblTabla_Materias.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jtblTabla_Materias.getSelectedRow() != -1) {
                    actualizarCampos();
                }
            }
        });

        // Añadir KeyListener para permitir solo letras y números con un máximo de 5 caracteres en el campo de código
        this.jtxtCodigoMateria.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isLetterOrDigit(c) || jtxtCodigoMateria.getText().length() >= 5) {
                    e.consume();  // Ignorar el evento si no es una letra o número o si la longitud es mayor a 5
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbtnAgregar = new javax.swing.JButton();
        jtbtnModificar = new javax.swing.JButton();
        jtbtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTabla_Materias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtCodigoMateria = new javax.swing.JTextField();
        jtxtNombreMateria = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 250));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbtnAgregar.setText("Agregar");
        jtbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAgregarActionPerformed(evt);
            }
        });
        add(jtbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 130, 40));

        jtbtnModificar.setText("Modificar");
        add(jtbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 130, 40));

        jtbtnEliminar.setText("Eliminar");
        add(jtbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 130, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jtblTabla_Materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Materia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblTabla_Materias.setGridColor(new java.awt.Color(102, 102, 102));
        jtblTabla_Materias.setRowHeight(30);
        jtblTabla_Materias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtblTabla_Materias);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, 350));

        jLabel3.setText("Nombre de la Materia");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 140, 30));

        jLabel4.setText("Código de la Materia");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 120, 30));
        add(jtxtCodigoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 150, 40));
        add(jtxtNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarTablaMaterias() {
        this.tabla.setRowCount(0);

        for (Materia m : this.materias) {
            this.tabla.addRow(new Object[]{m.getNombre(), m.getCodigo()});
        }
    }

    private void actualizarCampos() {
        int filaSeleccionada = this.jtblTabla_Materias.getSelectedRow();

        if (filaSeleccionada != -1) {
            String nombreMateriaSeleccionada = this.jtblTabla_Materias.getValueAt(filaSeleccionada, 0).toString();
            String codigoMateriaSeleccionada = this.jtblTabla_Materias.getValueAt(filaSeleccionada, 1).toString();

            this.jtxtNombreMateria.setText(nombreMateriaSeleccionada);
            this.jtxtCodigoMateria.setText(codigoMateriaSeleccionada);

            // Desactivar la edición del campo de código
            this.jtxtCodigoMateria.setEditable(false);
        }
    }
    
    public void limpiarCampos() {
        this.jtxtNombreMateria.setText("");
        this.jtxtCodigoMateria.setText("");
        this.jtxtCodigoMateria.setEditable(true);
    }


    private void jtbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAgregarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtbtnAgregarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private ArrayList<Materia> materias = new ArrayList<>();

    public ArrayList<Materia> getMaterias() {
        return this.materias;
    }

    public void setMaterias(ArrayList<Materia> materias) {
        this.materias = materias;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtblTabla_Materias;
    public javax.swing.JButton jtbtnAgregar;
    public javax.swing.JButton jtbtnEliminar;
    public javax.swing.JButton jtbtnModificar;
    public javax.swing.JTextField jtxtCodigoMateria;
    public javax.swing.JTextField jtxtNombreMateria;
    // End of variables declaration//GEN-END:variables

}
