/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Usuario;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Pestaña_Bloques extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Pestaña_Bloques() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Agregar_Bloque = new javax.swing.JButton();
        Btn_Modificar_Bloque = new javax.swing.JButton();
        Btn_Eliminar_Bloque = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxAula = new javax.swing.JComboBox<>();
        jComboBoxBloque = new javax.swing.JComboBox<>();
        Btn_Agregar_Aula = new javax.swing.JButton();
        Btn_Modificar_Aula = new javax.swing.JButton();
        Btn_Eliminar_Aula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 250));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Agregar_Bloque.setText("Agregar");
        Btn_Agregar_Bloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_BloqueActionPerformed(evt);
            }
        });
        add(Btn_Agregar_Bloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 110, 30));

        Btn_Modificar_Bloque.setText("Modificar");
        add(Btn_Modificar_Bloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 110, 30));

        Btn_Eliminar_Bloque.setText("Eliminar");
        add(Btn_Eliminar_Bloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 130, 30));

        jLabel2.setText("Aulas del bloque: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 110, 30));

        jLabel3.setText("Aula");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 30));

        jComboBoxAula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula" }));
        jComboBoxAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAulaActionPerformed(evt);
            }
        });
        add(jComboBoxAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, -1));

        jComboBoxBloque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bloque" }));
        jComboBoxBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBloqueActionPerformed(evt);
            }
        });
        add(jComboBoxBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));

        Btn_Agregar_Aula.setText("Agregar");
        Btn_Agregar_Aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_AulaActionPerformed(evt);
            }
        });
        add(Btn_Agregar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, 30));

        Btn_Modificar_Aula.setText("Modificar");
        add(Btn_Modificar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 110, 30));

        Btn_Eliminar_Aula.setText("Eliminar");
        add(Btn_Eliminar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Capacidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 440, 140));

        jLabel4.setText("Bloque");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void Btn_Agregar_BloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_BloqueActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Btn_Agregar_BloqueActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jComboBoxAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAulaActionPerformed

    private void jComboBoxBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBloqueActionPerformed

    private void Btn_Agregar_AulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_AulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Agregar_AulaActionPerformed

    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Agregar_Aula;
    public javax.swing.JButton Btn_Agregar_Bloque;
    public javax.swing.JButton Btn_Eliminar_Aula;
    public javax.swing.JButton Btn_Eliminar_Bloque;
    public javax.swing.JButton Btn_Modificar_Aula;
    public javax.swing.JButton Btn_Modificar_Bloque;
    public javax.swing.JComboBox<String> jComboBoxAula;
    public javax.swing.JComboBox<String> jComboBoxBloque;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
