/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.PeriodoAcademico;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Pestaña_Aulas extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Pestaña_Aulas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxBloque = new javax.swing.JComboBox<>();
        Btn_Agregar_Aula = new javax.swing.JButton();
        Btn_Modificar_Aula = new javax.swing.JButton();
        Btn_Eliminar_Aula = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNmbreAula = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAulas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxBloque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bloque" }));
        jComboBoxBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBloqueActionPerformed(evt);
            }
        });
        add(jComboBoxBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, 30));

        Btn_Agregar_Aula.setBackground(new java.awt.Color(153, 255, 153));
        Btn_Agregar_Aula.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Agregar_Aula.setText("Agregar");
        Btn_Agregar_Aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_AulaActionPerformed(evt);
            }
        });
        add(Btn_Agregar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 130, 40));

        Btn_Modificar_Aula.setText("Modificar");
        Btn_Modificar_Aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Modificar_AulaActionPerformed(evt);
            }
        });
        add(Btn_Modificar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 130, 40));

        Btn_Eliminar_Aula.setBackground(new java.awt.Color(204, 0, 0));
        Btn_Eliminar_Aula.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Eliminar_Aula.setText("Eliminar");
        add(Btn_Eliminar_Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 130, 40));

        jLabel4.setText("Bloque/s:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 110, 30));

        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabel2.setText("Tipo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jLabel5.setText("Capacidad:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));
        add(txtNmbreAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 210, 40));
        add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 210, 40));
        add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 210, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAulas.setGridColor(new java.awt.Color(102, 102, 102));
        jTableAulas.setRowHeight(30);
        jScrollPane1.setViewportView(jTableAulas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 390, 280));
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jComboBoxBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBloqueActionPerformed

    private void Btn_Agregar_AulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_AulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Agregar_AulaActionPerformed

    private void Btn_Modificar_AulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Modificar_AulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Modificar_AulaActionPerformed

    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Agregar_Aula;
    public javax.swing.JButton Btn_Eliminar_Aula;
    public javax.swing.JButton Btn_Modificar_Aula;
    public javax.swing.JComboBox<String> jComboBoxBloque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableAulas;
    public javax.swing.JTextField txtCapacidad;
    public javax.swing.JTextField txtNmbreAula;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

}
