/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.PeriodoAcademico;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Pestaña_PeriodoAcademico extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Pestaña_PeriodoAcademico() {
        initComponents();
        String columnas[] = {"Nombre","Fecha Inicio","Fecha Fin"};
        this.tabla.setColumnIdentifiers(columnas);
        this.Tabla_PeriodosAcademicos.setModel(tabla);
        this.Tabla_PeriodosAcademicos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (Tabla_PeriodosAcademicos.getSelectedRow() != -1) {
                    actualizarCampos();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Btn_Agregar_U = new javax.swing.JButton();
        Btn_Modificar_U = new javax.swing.JButton();
        Btn_Eliminar_U = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_PeriodosAcademicos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 250));
        setPreferredSize(new java.awt.Dimension(930, 490));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Fecha Fin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 110, 30));

        Btn_Agregar_U.setText("Agregar");
        Btn_Agregar_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_UActionPerformed(evt);
            }
        });
        add(Btn_Agregar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 130, 40));

        Btn_Modificar_U.setText("Modificar");
        add(Btn_Modificar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 130, 40));

        Btn_Eliminar_U.setText("Eliminar");
        add(Btn_Eliminar_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 130, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_PeriodosAcademicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Periodo Academico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_PeriodosAcademicos.setGridColor(new java.awt.Color(102, 102, 102));
        Tabla_PeriodosAcademicos.setRowHeight(30);
        Tabla_PeriodosAcademicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Tabla_PeriodosAcademicos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 370, 350));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 110, 30));

        jLabel3.setText("Fecha Inicio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 110, 30));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 150, 40));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, 40));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    public void ActualizarTablaPeriodos() {
        this.tabla.setRowCount(0);
        for (PeriodoAcademico u : this.PeriodosAcademicos) {
            this.tabla.addRow(new Object[]{u.getNombre(),u.getFecha_inicio(),u.getFecha_fin()});
        }
    }

    private void actualizarCampos() {
        for(PeriodoAcademico u : this.PeriodosAcademicos){
            if(u.getNombre().matches(this.Tabla_PeriodosAcademicos.getValueAt(this.Tabla_PeriodosAcademicos.getSelectedRow(), 0).toString())){
                this.jTextField1.setText(u.getNombre());
                this.jDateChooser1.setDate(u.getFecha_inicio());
                this.jDateChooser2.setDate(u.getFecha_fin());
                return;
            }
        }
    }
    private void Btn_Agregar_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_UActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Btn_Agregar_UActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    public DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer todas las celdas no editables
        }
    };
    private ArrayList<PeriodoAcademico> PeriodosAcademicos = new ArrayList<>();

    public ArrayList<PeriodoAcademico> getPeriodosAcademicos() {
        return this.PeriodosAcademicos;
    }

    public void setPeriodosAcademicos(ArrayList<PeriodoAcademico> PeriodosAcademicos) {
        this.PeriodosAcademicos = PeriodosAcademicos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Agregar_U;
    public javax.swing.JButton Btn_Eliminar_U;
    public javax.swing.JButton Btn_Modificar_U;
    public javax.swing.JTable Tabla_PeriodosAcademicos;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
